### ISSUE TITLE
Error since upgrading to 1.0.3.0

### ISSUE THREAD

**Issue by UweKeim** [NLua/KeraLua#40]
Since upgrading to 1.0.3.0, I get a compilation error:

(In German)

> ASPNETCOMPILER : error ASPCONFIG: Die Datei oder Assembly "KeraLua, Version=1.0.3.0, Culture=neutral, PublicKeyToken=6a194c04b9c89217" oder eine Abhängigkeit davon wurde nicht gefunden. Die Signatur mit starkem Namen konnte nicht überprüft werden. Die Assembly wurde möglicherweise geändert oder verzögert aber nicht vollständig mit dem richtigen privaten Schlüssel signiert. (Ausnahme von HRESULT: 0x80131045) [c:\MyMvcWebApp\MyMvcWebApp.csproj]

Manually translated to English, the core error text reads:

> The signature with a strong name could not be verified. Assembly may have been changed or delayed but not fully signed with the correct private key.

**My question:**

What am I doing wrong here? How can I fix this behaviour?

**Comment by viniciusjarina** [comment]
* Fixed https://github.com/NLua/KeraLua/releases/tag/v1.0.4
